### PR TITLE
Make huggingface_hub version more flexible

### LINKED ISSUE #13: update huggingface-hub version
Version conflicts using the latest transformers.

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.26.0 requires huggingface-hub<1.0,>=0.11.0, but you have huggingface-hub 0.8.1 which is incompatible.
Successfully installed huggingface-hub-0.8.1
```

can you update the version???

### PR DESCRIPTION
**Pull request by osanseviero**
cc @wauplin 

Fixes #13

### CODE REVIEW

**Comment by Wauplin** [comment]
Thanks for the quick fix @osanseviero :)

**Comment by adrianeboyd** [comment]
The API for `huggingface_hub` seems like it's been kind of unstable in the past (obviously not unexpected for v0.x) and we don't have any kind of tests/CI for this repo, so I'm a little hesitant to make this exact change.

On the other hand, I suppose this doesn't really break much on our end of things if new installs aren't working for a short period, so if you'd prefer this setup and can jump in to fix it if it breaks, that would be okay.

We usually keep the same settings (+ dev requirements for any had tests/CI) in `requirements.txt`, so either that should also be synced or maybe we should consider removing `requirements.txt` because it's not really used here.

**Comment by Wauplin** [comment]
> The API for huggingface_hub seems like it's been kind of unstable in the past (obviously not unexpected for v0.x) and we don't have any kind of tests/CI for this repo, so I'm a little hesitant to make this exact change.

@adrianeboyd You made a good point here. Luckily, we just started to new CI pipeline directly on `huggingface_hub` that runs tests for external contrib libraries. The goal is to make end-2-end tests and check that no `FutureWarning` is triggered. If we change an API that breaks `spacy-huggingface-hub` somewhere, we will notice it enough in advance to change it. Tests are run on the latest dev version of `hfh` and usually when we introduce a breaking change, it is first deprecated (e.g. trigger a warning) for a few versions before being removed.

**Comment by adrianeboyd** [comment]
Sounds good!

**Pull request merged**
